"""Add reset_token fields to partners table

Revision ID: b4b96fc5b6ff
Revises: cfb85fa2b18b
Create Date: 2025-12-08 16:30:16.474162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4b96fc5b6ff'
down_revision = 'cfb85fa2b18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before adding them
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_columns = [col['name'] for col in inspector.get_columns('partners')]
    
    with op.batch_alter_table('partners', schema=None) as batch_op:
        if 'reset_token' not in existing_columns:
            batch_op.add_column(sa.Column('reset_token', sa.String(length=255), nullable=True))
        if 'reset_token_expires' not in existing_columns:
            batch_op.add_column(sa.Column('reset_token_expires', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('partners', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expires')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
